services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-kraft
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LOG_DIRS=/opt/bitnami/kafka/data
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_MODE=true
      - KAFKA_KRAFT_CLUSTER_ID=UlZ2OzYHS6GJ6aRqezl4eQ  # Use a consistent Cluster ID
    volumes:
      - kafka-data:/opt/bitnami/kafka/data
    networks:
      - kafka-net
    ports:
      - "9092:9092"
      - "9093:9093"

networks:
  kafka-net:
    external: true

volumes:
  kafka-data:
    external: true
