/**
 * PubTator3 API
 * This API provides functionality to retrieve biomedical text annotations and related entities. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package notes.common.pubtator3.reference.client.models


/**
 * 
 * @param type The type of biomedical entity (e.g., gene, chemical, disease).
 * @param start The starting index of the annotation in the text.
 * @param end The ending index of the annotation in the text.
 * @param text The annotated text.
 * @param id The identifier for the entity.
 */
data class Annotation (

    /* The type of biomedical entity (e.g., gene, chemical, disease). */
    val type: kotlin.String? = null,
    /* The starting index of the annotation in the text. */
    val start: kotlin.Int? = null,
    /* The ending index of the annotation in the text. */
    val end: kotlin.Int? = null,
    /* The annotated text. */
    val text: kotlin.String? = null,
    /* The identifier for the entity. */
    val id: kotlin.String? = null
) {
}