/**
 * PubTator3 API
 * This API provides functionality to retrieve biomedical text annotations and related entities. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package notes.common.pubtator3.reference.client.models

/**
 * 
 * @param results 
 * @param facets 
 * @param pageSize Number of results per page.
 * @param current Current page number.
 * @param count Total number of search results.
 * @param totalPages Total number of pages.
 */
data class InlineResponse2001 (

    val results: kotlin.Array<InlineResponse2001Results>? = null,
    val facets: InlineResponse2001Facets? = null,
    /* Number of results per page. */
    val pageSize: kotlin.Int? = null,
    /* Current page number. */
    val current: kotlin.Int? = null,
    /* Total number of search results. */
    val count: kotlin.Int? = null,
    /* Total number of pages. */
    val totalPages: kotlin.Int? = null
) {
}