/**
 * PubTator3 API
 * This API provides functionality to retrieve biomedical text annotations and related entities. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package notes.common.pubtator3.reference.client.models


/**
 *
 * @param type Type of relationship (e.g., negative_correlate, treat).
 * @param source The source entity ID.
 * @param target The target entity ID.
 * @param publications Number of publications that mention this relationship.
 */
data class InlineResponse2002 (

    /* Type of relationship (e.g., negative_correlate, treat). */
    val type: kotlin.String? = null,
    /* The source entity ID. */
    val source: kotlin.String? = null,
    /* The target entity ID. */
    val target: kotlin.String? = null,
    /* Number of publications that mention this relationship. */
    val publications: kotlin.Int? = null
) {
}