/**
 * PubTator3 API
 * This API provides functionality to retrieve biomedical text annotations and related entities. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package notes.common.pubtator3.reference.client.models


/**
 * Citation details in different formats.
 * @param nLM National Library of Medicine citation format.
 * @param bibTeX Citation in BibTeX format.
 */
data class InlineResponse2001Citations (

    /* National Library of Medicine citation format. */
    val nLM: kotlin.String? = null,
    /* Citation in BibTeX format. */
    val bibTeX: kotlin.String? = null
) {
}