/**
 * PubTator3 API
 * This API provides functionality to retrieve biomedical text annotations and related entities. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package notes.common.pubtator3.reference.client.models

/**
 * 
 * @param journal 
 * @param year 
 */
data class InlineResponse2001Facets (

    val journal: kotlin.Array<InlineResponse2001FacetsJournal>? = null,
    val year: kotlin.Array<InlineResponse2001FacetsYear>? = null
) {
}