/**
 * ollama API
 * API for interacting with ollama models
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param model The model name (required)
 * @param prompt Text to generate embeddings for
 * @param options Additional model parameters
 */
data class ApiEmbeddingsBody (

    /* The model name (required) */
    val model: kotlin.String? = null,
    /* Text to generate embeddings for */
    val prompt: kotlin.String? = null,
    /* Additional model parameters */
    val options: kotlin.Any? = null
) {
}