/**
 * ollama API
 * API for interacting with ollama models
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param model The model name (required)
 * @param prompt The prompt to generate a response for
 * @param options Additional model parameters
 * @param system System prompt to override the model's definition
 * @param template The full prompt or prompt template to override the model's definition
 */
data class ApiGenerateBody (

    /* The model name (required) */
    val model: kotlin.String? = null,
    /* The prompt to generate a response for */
    val prompt: kotlin.String? = null,
    /* Additional model parameters */
    val options: kotlin.Any? = null,
    /* System prompt to override the model's definition */
    val system: kotlin.String? = null,
    /* The full prompt or prompt template to override the model's definition */
    val template: kotlin.String? = null
) {
}