/**
 * ollama API
 * API for interacting with ollama models
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param license 
 * @param modelfile 
 * @param parameters 
 * @param template 
 */
data class InlineResponse2003 (

    val license: kotlin.String? = null,
    val modelfile: kotlin.String? = null,
    val parameters: kotlin.String? = null,
    val template: kotlin.String? = null
) {
}