/**
 * ollama API
 * API for interacting with ollama models
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param model 
 * @param createdAt 
 * @param response 
 * @param done 
 * @param totalDuration 
 * @param loadDuration 
 * @param sampleCount 
 * @param sampleDuration 
 * @param promptEvalCount 
 * @param promptEvalDuration 
 * @param evalCount 
 * @param evalDuration 
 * @param context 
 */
data class InlineResponse200 (

    val model: kotlin.String? = null,
    val createdAt: java.time.LocalDateTime? = null,
    val response: kotlin.String? = null,
    val done: kotlin.Boolean? = null,
    val totalDuration: kotlin.Int? = null,
    val loadDuration: kotlin.Int? = null,
    val sampleCount: kotlin.Int? = null,
    val sampleDuration: kotlin.Int? = null,
    val promptEvalCount: kotlin.Int? = null,
    val promptEvalDuration: kotlin.Int? = null,
    val evalCount: kotlin.Int? = null,
    val evalDuration: kotlin.Int? = null,
    val context: kotlin.Array<kotlin.Int>? = null
) {
}