package notes.common.ollama.model

/**
 * ollama API
 * API for interacting with ollama models
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 *
 * @param model The model name (required)
 * @param prompt The prompt to generate a response for
 * @param options Additional model parameters
 * @param system System prompt to override the model's definition
 * @param template The full prompt or prompt template to override the model's definition
 */
data class OllamaGenerateRequestBody (

    /* The model name (required) */
    val model: String? = null,
    /* The prompt to generate a response for */
    val prompt: String? = null,
    /* Whether to stream the response */
    val stream: Boolean? = null,
    /* Additional model parameters */
    val options: Any? = null,
    /* System prompt to override the model's definition */
    val system: String? = null,
    /* The full prompt or prompt template to override the model's definition */
    val template: String? = null
) {
}